### ISSUE TITLE
Clarify absence of licensing for job descriptions

### ISSUE THREAD

**Issue by DuaneOBrien** [todogroup/job-descriptions#6]
Given that these job descriptions have been collected from around the web, we should clarify that these job descriptions are provided without a license, and are provided for examples.

**Comment by gyehuda** [comment]
Without being explicit about licensing, I have updated the readme to suggest readers should use these examples to inform you when creating of a job description, and to get a sense of the types of roles found in OSPOs. That they may contribute a job posting to this repo from a job description they _have the right to share_, and that they include a link to the public source (to tacitly indicate the public nature of this content).

Furthermore I clarified this is not a listing of currently available roles.
